api_version = "2025-07"

[[extensions]]
name = "Extra Surcharge"
handle = "extra-surcharge"
uid = "2009ae03-b390-9bf4-fedb-ae9dbd6cde8b3a9ade62"
type = "function"
description = "Apply a configurable percentage surcharge to the cart subtotal"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/extra-charge"
  details = "/app/extra-charge"
